# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stat_bot.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(601, 366)
        mainWindow.setStyleSheet("background-color: rgb(237, 245, 255);")
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setAccessibleName("")
        self.centralwidget.setObjectName("centralwidget")
        self.date = QtWidgets.QDateTimeEdit(self.centralwidget)
        self.date.setGeometry(QtCore.QRect(210, 160, 222, 35))
        self.date.setAccessibleDescription("")
        self.date.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 16pt \"Times New Roman\";")
        self.date.setDateTime(QtCore.QDateTime(QtCore.QDate(2021, 1, 1), QtCore.QTime(0, 0, 0)))
        self.date.setMaximumDateTime(QtCore.QDateTime(QtCore.QDate(2031, 12, 31), QtCore.QTime(23, 59, 59)))
        self.date.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2020, 5, 14), QtCore.QTime(0, 0, 0)))
        self.date.setObjectName("date")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(130, 210, 157, 40))
        self.pushButton_2.setStyleSheet("border-bottom-color: rgb(199, 199, 199);\n"
"font: 16pt \"Times New Roman\";\n"
"background-color: rgb(221, 221, 221);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(350, 210, 93, 40))
        self.pushButton.setStyleSheet("border-bottom-color: rgb(199, 199, 199);\n"
"font: 16pt \"Times New Roman\";\n"
"background-color: rgb(221, 221, 221);")
        self.pushButton.setObjectName("pushButton")
        self.login = QtWidgets.QLineEdit(self.centralwidget)
        self.login.setGeometry(QtCore.QRect(40, 60, 222, 32))
        self.login.setStyleSheet("font: 14pt \"Times New Roman\";\n"
"background-color: rgb(255, 255, 255);")
        self.login.setObjectName("login")
        self.password = QtWidgets.QLineEdit(self.centralwidget)
        self.password.setGeometry(QtCore.QRect(330, 60, 222, 32))
        self.password.setStyleSheet("font: 14pt \"Times New Roman\";\n"
"background-color: rgb(255, 255, 255);")
        self.password.setObjectName("password")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 20, 192, 26))
        self.label.setStyleSheet("\n"
"font: 14pt \"Times New Roman\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(330, 20, 211, 26))
        self.label_2.setStyleSheet("\n"
"font: 14pt \"Times New Roman\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(110, 120, 381, 26))
        self.label_3.setStyleSheet("\n"
"font: 14pt \"Times New Roman\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(250, 320, 301, 20))
        self.label_4.setStyleSheet("font: 9pt \"Times New Roman\";")
        self.label_4.setObjectName("label_4")
        mainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Сборщик статистики"))
        self.pushButton_2.setText(_translate("mainWindow", "Подтвердить"))
        self.pushButton.setText(_translate("mainWindow", "Начать"))
        self.label.setText(_translate("mainWindow", "Введите Ваш логин:"))
        self.label_2.setText(_translate("mainWindow", "Введите Ваш пароль:"))
        self.label_3.setText(_translate("mainWindow", "Задайте точку отсчета для статистики:"))
        self.label_4.setText(_translate("mainWindow", "<html><head/><body><p>Сделано с любовью <a href=\"https://t.me/tritium\"><span style=\" text-decoration: underline; color:#0000ff;\">@tritum</span></a> и <a href=\"https://t.me/cobaltCorsair\"><span style=\" text-decoration: underline; color:#0000ff;\">@cobaltCorsair</span></a></p></body></html>"))
